baseURL = "https://listings2.netlify.app/"
languageCode = "en-us"
summaryLength = 20
[[menu.footer]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[params]
cloudinary_url = "https://res.cloudinary.com/realestate2/image/upload"
[outputs]
home = ["HTML", "RSS", "JSON"]
[taxonomies]
category = "categories"
city = "cities"
property = "properties"
state = "states"
status = "status"
tag = "tags"
zip = "zip-codes"
featured = "featured"
