baseURL = "https://www.pathfinderscarpetcleaning.com/"
languageCode = "en-us"
summaryLength = 20
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[outputs]
home = ["HTML", "RSS", "JSON"]
[taxonomies]
category = "categories"
city = "city"
property = "property"
state = "state"
status = "status"
tag = "tags"
zip = "zip"
featured = "featured"