---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 
sections:
- type: document
  path: data/profile.yml
  label: Profile
- type: document
  path: data/appearance.yml
  label: Appearance
- type: document
  path: data/homelayout.yml
  label: Home Layout
- type: directory
  path: content
  label: Pages
  create: documents
  match: "*"
  templates:
  - pages
- type: directory
  path: content/offices
  label: Offices
  create: documents
  match: "**/*"
  templates:
  - offices
- type: heading
  label: Blog
- type: directory
  path: content/blog
  label: Add Post
  create: documents
  match: "**/*"
  templates:
  - blog
- type: heading
  label: Default Pages
- type: directory
  path: content/our-team
  label: My Team
  create: documents
  match: "**/*"
  templates:
  - our-team
- type: document
  path: content/testimonials/_index.md
  label: Testimonials
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.76.5
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.76.5
